/* Generated by mkromfs. Edit with caution. */
#include <rtthread.h>
#include <dfs_romfs.h>


static const struct romfs_dirent _romfs_root_mmt[] = {
    {ROMFS_DIRENT_DIR, "sd", 0, 0}, 
    {ROMFS_DIRENT_DIR, "tmp", 0, 0}, 
    {ROMFS_DIRENT_DIR, "flash", 0, 0}
};

static const struct romfs_dirent _romfs_root[] = {
    {ROMFS_DIRENT_DIR,  "dev", 0, 0},
    {ROMFS_DIRENT_DIR,  "mnt", (rt_uint8_t *)_romfs_root_mmt, sizeof(_romfs_root_mmt)/sizeof(_romfs_root_mmt[0])}, 
};
const struct romfs_dirent romfs_root =
{
    ROMFS_DIRENT_DIR, "/", (rt_uint8_t *)_romfs_root, sizeof(_romfs_root) / sizeof(_romfs_root[0])
};

#include <dfs_fs.h>
int rt_hw_romfs_init(void)
{
    dfs_mount(RT_NULL, "/", "rom", 0, &romfs_root);

    return 0;
}
INIT_EXPORT(rt_hw_romfs_init, "4.end"); 

