from building import *

cwd = GetCurrentDir()

# add the general drivers.
src = Split("""
board.c
drv_mpu.c
drv_cache.c
drv_romfs.c
""")

if GetDepend(['RT_USING_SERIAL']):
    src += ['drv_usart.c']

if GetDepend(['BSP_USING_USBD']):
    src += ['drv_usbd.c']

if GetDepend(['BSP_USING_USBH']):
    src += ['drv_usbh.c']

if GetDepend(['BSP_USING_SDRAM']):
    src += ['drv_sdram.c']

if GetDepend(['BSP_USING_LCD']):
    src += ['drv_ltdc.c']

if GetDepend(['BSP_USING_PIN']):
    src += ['drv_gpio.c']

if GetDepend(['RT_USING_I2C_BITOPS']):
    src += ['drv_i2c.c']

if GetDepend(['BSP_USING_QSPI_FLASH']):
    src += ['drv_qspi.c', 'stm32_qspi.c']

if GetDepend(['BSP_USING_RAMDISK']):
    src += ['drv_ramdisk.c']

CPPPATH = [cwd]

group = DefineGroup('Drivers', src, depend = [''], CPPPATH = CPPPATH)

objs = []
objs += group
list = os.listdir(cwd)

for d in list:
    path = os.path.join(cwd, d)
    if os.path.isfile(os.path.join(path, 'SConscript')):
        objs = objs + SConscript(os.path.join(d, 'SConscript'))

Return('objs')
